;;
;;  walter-light-theme.el
;;
;;  * btw, `M-x list-faces-display` shows all possible faces
;;

(deftheme walter-light "Walter in the Light" :background-mode "light" :kind "color-scheme" :family "light")
  (custom-theme-set-faces 'walter-light
   '(default ((t (:foreground "#24292e" :background "#f8f8f8" ))))
   '(cursor ((t (:foreground "#000000" :background "#00aa00" ))))
   '(fringe ((t (:background "#f8f8f8" ))))
   '(line-number ((t (:foreground "#0077bb" :background "#eeeeee" ))))
   '(line-number-current-line ((t (:foreground "#000000" :background "#eeeeee" ))))
   '(mode-line ((t (:foreground "#000000" :background "#eeeeee" ))))
   '(region ((t (:background "#c0e0ee" ))))
   '(secondary-selection ((t (:background "#984ea5" ))))
   '(font-lock-builtin-face ((t (:foreground "#000000" ))))
   '(font-lock-comment-face ((t (:foreground "#006600" ))))
   '(font-lock-constant-face ((t (:foreground "#006600"))))
   '(font-lock-doc-face ((t (:foreground "#006600" ))))
   '(font-lock-doc-markup-face ((t (:foreground "#006600" ))))
   '(font-lock-function-name-face ((t (:foreground "#000000"))))
   '(font-lock-keyword-face ((t (:foreground "#990000" ))))
   '(font-lock-number-face ((t (:foreground "#006600"))))
   '(font-lock-operator-face ((t (:foreground "#000000"))))
   '(font-lock-punctuation-face ((t (:foreground "#000000"))))
   '(font-lock-misc-punctuation-face ((t (:foreground "#000000"))))
   '(font-lock-preprocessor-face ((t (:foreground "#000000"))))
   '(font-lock-string-face ((t (:foreground "#0033aa" ))))
   '(font-lock-type-face ((t (:foreground "#990000" ))))
   '(font-lock-variable-name-face ((t (:foreground "#000000"))))
   '(minibuffer-prompt ((t (:foreground "#111111" :bold t ))))
   '(font-lock-warning-face ((t (:foreground "red" :bold t ))))
   )

;;;###autoload
(and load-file-name
    (boundp 'custom-theme-load-path)
    (add-to-list 'custom-theme-load-path
                 (file-name-as-directory
                  (file-name-directory load-file-name))))

(provide-theme 'walter-light)


;; (custom-theme-set-faces
;;  'my-theme-name
;;  '(default ((t (:inherit nil :stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :extend nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
;;  '(cursor ((t (:background "black" :foreground "#00cc00"))))
;;  '(fixed-pitch ((t (:family "Monospace"))))
;;  '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
;;  '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
;;  '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
;;  '(minibuffer-prompt ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "medium blue"))))
;;  '(highlight ((((class color) (min-colors 88) (background light)) (:background "darkseagreen2")) (((class color) (min-colors 88) (background dark)) (:background "darkolivegreen")) (((class color) (min-colors 16) (background light)) (:background "darkseagreen2")) (((class color) (min-colors 16) (background dark)) (:background "darkolivegreen")) (((class color) (min-colors 8)) (:foreground "black" :background "green")) (t (:inverse-video t))))
;;  '(region ((((class color) (min-colors 88) (background dark)) (:extend t :background "blue3")) (((class color) (min-colors 88) (background light)) (:extend t :background "lightgoldenrod2")) (((class color) (min-colors 16) (background dark)) (:extend t :background "blue3")) (((class color) (min-colors 16) (background light)) (:extend t :background "lightgoldenrod2")) (((class color) (min-colors 8)) (:extend t :foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:extend t :background "gray"))))
;;  '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
;;  '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
;;  '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
;;  '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
;;  '(font-lock-builtin-face ((t (:foreground "brightwhite"))))
;;  '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
;;  '(font-lock-comment-face ((t (:foreground "green"))))
;;  '(font-lock-constant-face ((((class grayscale) (background light)) (:underline (:color foreground-color :style line :position nil) :weight bold :foreground "LightGray")) (((class grayscale) (background dark)) (:underline (:color foreground-color :style line :position nil) :weight bold :foreground "Gray50")) (((class color) (min-colors 88) (background light)) (:foreground "dark cyan")) (((class color) (min-colors 88) (background dark)) (:foreground "Aquamarine")) (((class color) (min-colors 16) (background light)) (:foreground "CadetBlue")) (((class color) (min-colors 16) (background dark)) (:foreground "Aquamarine")) (((class color) (min-colors 8)) (:foreground "magenta")) (t (:underline (:color foreground-color :style line :position nil) :weight bold))))
;;  '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
;;  '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
;;  '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
;;  '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
;;  '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
;;  '(font-lock-function-name-face ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:weight bold :foreground "blue")) (t (:weight bold :inverse-video t))))
;;  '(font-lock-keyword-face ((((class grayscale) (background light)) (:weight bold :foreground "LightGray")) (((class grayscale) (background dark)) (:weight bold :foreground "DimGray")) (((class color) (min-colors 88) (background light)) (:foreground "Purple")) (((class color) (min-colors 88) (background dark)) (:foreground "Cyan1")) (((class color) (min-colors 16) (background light)) (:foreground "Purple")) (((class color) (min-colors 16) (background dark)) (:foreground "Cyan")) (((class color) (min-colors 8)) (:weight bold :foreground "cyan")) (t (:weight bold))))
;;  '(font-lock-negation-char-face ((t nil)))
;;  '(font-lock-number-face ((t nil)))
;;  '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
;;  '(font-lock-operator-face ((t nil)))
;;  '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
;;  '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
;;  '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
;;  '(font-lock-punctuation-face ((t nil)))
;;  '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
;;  '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
;;  '(font-lock-string-face ((((class grayscale) (background light)) (:slant italic :foreground "DimGray")) (((class grayscale) (background dark)) (:slant italic :foreground "LightGray")) (((class color) (min-colors 88) (background light)) (:foreground "VioletRed4")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSalmon")) (((class color) (min-colors 16) (background light)) (:foreground "RosyBrown")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSalmon")) (((class color) (min-colors 8)) (:foreground "green")) (t (:slant italic))))
;;  '(font-lock-type-face ((((class grayscale) (background light)) (:weight bold :foreground "Gray90")) (((class grayscale) (background dark)) (:weight bold :foreground "DimGray")) (((class color) (min-colors 88) (background light)) (:foreground "ForestGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 16) (background light)) (:foreground "ForestGreen")) (((class color) (min-colors 16) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:underline (:color foreground-color :style line :position nil) :weight bold))))
;;  '(font-lock-variable-name-face ((((class grayscale) (background light)) (:slant italic :weight bold :foreground "Gray90")) (((class grayscale) (background dark)) (:slant italic :weight bold :foreground "DimGray")) (((class color) (min-colors 88) (background light)) (:foreground "sienna")) (((class color) (min-colors 88) (background dark)) (:foreground "LightGoldenrod")) (((class color) (min-colors 16) (background light)) (:foreground "DarkGoldenrod")) (((class color) (min-colors 16) (background dark)) (:foreground "LightGoldenrod")) (((class color) (min-colors 8)) (:weight light :foreground "yellow")) (t (:slant italic :weight bold))))
;;  '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
;;  '(font-lock-warning-face ((t (:inherit (error)))))
;;  '(button ((t (:inherit (link)))))
;;  '(link ((t (:underline (:color foreground-color :style line :position nil) :foreground "cyan1"))))
;;  '(link-visited ((t (:foreground "violet" :inherit (link)))))
;;  '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
;;  '(header-line ((t (:underline (:color foreground-color :style line :position nil) :inverse-video nil :inherit (mode-line)))))
;;  '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
;;  '(mode-line ((t (:box (:line-width (1 . -1) :color nil :style released-button) :foreground "black" :background "grey75"))))
;;  '(mode-line-buffer-id ((t (:weight bold))))
;;  '(mode-line-emphasis ((t (:weight bold))))
;;  '(mode-line-highlight ((t (:inherit (highlight)))))
;;  '(mode-line-inactive ((t (:weight light :box (:line-width (1 . -1) :color "grey40" :style nil) :foreground "grey80" :background "grey30" :inherit (mode-line)))))
;;  '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
;;  '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
;;  '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:distant-foreground "black" :background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:distant-foreground "white" :background "paleturquoise4")) (((class color) (min-colors 16)) (:distant-foreground "white" :background "turquoise3")) (((class color) (min-colors 8)) (:distant-foreground "white" :background "turquoise3")) (t (:underline (:color foreground-color :style line :position nil)))))
;;  '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
;;  '(next-error ((t (:inherit (region)))))
;;  '(query-replace ((t (:inherit (isearch))))))

;; (provide-theme 'my-theme-name)
